In [2]:
import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

In [3]:
from sklearn import datasets
cal = datasets.fetch_california_housing()

**Task 1**

In [6]:
cal

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------

a.

In [15]:
X = cal['data']
y = cal['target']
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
CV_score = cross_val_score(LinearRegression(), X, y, cv=5,scoring = 'r2')
CV_score

array([0.54866323, 0.46820691, 0.55078434, 0.53698703, 0.66051406])

In [14]:
CV_score.mean()

0.5530311140279232

In [15]:
from sklearn.ensemble import GradientBoostingRegressor
CV_score = cross_val_score(GradientBoostingRegressor(), X, y, cv=5,scoring = 'r2')
CV_score

array([0.60254206, 0.69877396, 0.71802327, 0.65023363, 0.6797686 ])

In [16]:
CV_score.mean()

0.6698683034111084

b.

In [21]:
CV_score = cross_val_score(GradientBoostingRegressor(n_estimators=200), X, y, cv=5,scoring = 'r2')
CV_score.mean()

0.6791972219022272

In [25]:
CV_score = cross_val_score(GradientBoostingRegressor(n_estimators=50), X, y, cv=5,scoring = 'r2')
CV_score.mean()

0.6329935193723815

In [23]:
CV_score = cross_val_score(GradientBoostingRegressor(max_depth=6), X, y, cv=5,scoring = 'r2')
CV_score.mean()

0.6777626176749213

In [26]:
CV_score = cross_val_score(GradientBoostingRegressor(max_depth=7), X, y, cv=5,scoring = 'r2')
CV_score.mean()

0.6650370470445139

In [27]:
CV_score = cross_val_score(GradientBoostingRegressor(learning_rate=0.2), X, y, cv=5,scoring = 'r2')
CV_score.mean()

0.6725962780428302

In [29]:
CV_score = cross_val_score(GradientBoostingRegressor(n_estimators=200, max_depth=6), X, y, cv=5,scoring = 'r2')
CV_score.mean()

0.6746411439237815

c.

The gradient boosting tree regression model performs better than the linear regression model. The gradient model seems to improve when the number of estimators is increased and does worse when this number is decreased. It also does better when max depth is increased to 6 but does worse when max depth is 7. It also performs better when the learning rate is increased

__Task 2__ 

a.

In [12]:
import numpy as np
X = cal['data']
y = cal['target'] > 2 
y = y*1
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
CV_accuracy = cross_val_score(LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=350), X, y, cv=5, scoring='accuracy')
CV_accuracy

array([0.81012352, 0.79699612, 0.77616279, 0.7313469 , 0.82384299])

In [13]:
CV_accuracy.mean()

0.7876944631525499

In [17]:
from sklearn.ensemble import GradientBoostingClassifier
CV_score = cross_val_score(GradientBoostingClassifier(), X, y, cv=5,scoring = 'accuracy')
CV_score

array([0.79099055, 0.75436047, 0.80765504, 0.75339147, 0.82650836])

In [18]:
CV_score.mean()

0.7865811781882253

b.

In [19]:
CV_score = cross_val_score(GradientBoostingClassifier(n_estimators=200), X, y, cv=5,scoring = 'accuracy')
CV_score.mean()

0.7714162499714933

In [20]:
CV_score = cross_val_score(GradientBoostingClassifier(n_estimators=50), X, y, cv=5,scoring = 'accuracy')
CV_score.mean()

0.7886656026909178

In [21]:
CV_score = cross_val_score(GradientBoostingClassifier(max_depth=7), X, y, cv=5,scoring = 'accuracy')
CV_score.mean()

0.7561069936773317

In [22]:
CV_score = cross_val_score(GradientBoostingClassifier(max_depth=1), X, y, cv=5,scoring = 'accuracy')
CV_score.mean()

0.800632469404108

In [23]:
CV_score = cross_val_score(GradientBoostingClassifier(learning_rate=0.2), X, y, cv=5,scoring = 'accuracy')
CV_score.mean()

0.7645862041898267

In [37]:
CV_score = cross_val_score(GradientBoostingClassifier(n_estimators=50, max_depth=1), X, y, cv=5,scoring = 'accuracy')
CV_score.mean()

0.7842564767391835

c.

In [28]:
from sklearn.metrics import roc_auc_score
CV_auc = cross_val_score(LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=350), X, y, cv=5, scoring='roc_auc')
CV_auc.mean()

0.8677105931720892

In [29]:
CV_score = cross_val_score(GradientBoostingClassifier(), X, y, cv=5,scoring = 'roc_auc')
CV_score.mean()

0.889758605688564

In [30]:
CV_score = cross_val_score(GradientBoostingClassifier(n_estimators=200), X, y, cv=5,scoring = 'roc_auc')
CV_score.mean()

0.8770312655444119

In [31]:
CV_score = cross_val_score(GradientBoostingClassifier(n_estimators=50), X, y, cv=5,scoring = 'roc_auc')
CV_score.mean()

0.8885778804946044

In [32]:
CV_score = cross_val_score(GradientBoostingClassifier(max_depth=7), X, y, cv=5,scoring = 'roc_auc')
CV_score.mean()

0.8508402508186219

In [33]:
CV_score = cross_val_score(GradientBoostingClassifier(max_depth=1), X, y, cv=5,scoring = 'roc_auc')
CV_score.mean()

0.8856358072657521

In [41]:
CV_score = cross_val_score(GradientBoostingClassifier(learning_rate=0.05), X, y, cv=5,scoring = 'roc_auc')
CV_score.mean()

0.887257563922222

In [38]:
CV_score = cross_val_score(GradientBoostingClassifier(n_estimators=50, max_depth=1), X, y, cv=5,scoring = 'roc_auc')
CV_score.mean()

0.8677687371898439

d. 
The logistic regression model performs slightly better than the gradient boosting tree classification model according to accuracy scoring, although they are very similar. When using AUC_ROC scoring, however, gradient boosting performs better. When using accuracy scoring, the gradient boosting model seems to improve with a lower number of estimators and a lower maximum depth. It does worse with a higher learning rate. When using ROC_AUC scoring, while some of the modifications of meta-parameters were similar to the original score, specifically lower numbers of estimators, maximum depth, and learning rate, none caused a better performance. 

In [43]:
from sklearn.dummy import DummyClassifier
dummy = DummyClassifier().fit(X, y)
dummy.predict(X)
dummy.score(X, y)

0.5137596899224807

Compared to a trivial classifier, both the logistic regression model and gradient boosting tree classification model performed very well. These are both much better classifiers than a trivial one. 